### ISSUE TITLE
[Compatibility] Vertical planks and slabs

### ISSUE THREAD

**Issue by i-o-u** [cech12/ExtendedMushrooms#17]
Btw a huge bonus of adding compatibility for Quark is you can get featured on their website: https://quark.vazkii.net/#features (click friends)

**Comment by cech12** [comment]
Hey thank you, thats a good idea! :) It would also be nice if the features "Stained Planks", "Variant Bookshelfs", "Variant Shelfs" and "Variant Ladders" are also be supported. :)

How to be a friend of Quark:
https://github.com/Vazkii/Quark/issues/1939

Problem: Mod should be vanilla like. Maybe planned alchemy and magic should be in another mod?!

**Comment by i-o-u** [comment]
About the planned alchemy and magic, if you plan on adding potion effects quark and their friend mods would likely support that since [Buzzier Bees](https://www.curseforge.com/minecraft/mc-mods/buzzier-bees), [Upgrade Aquatic](https://www.curseforge.com/minecraft/mc-mods/upgrade-aquatic) and [Atmospheric](https://www.curseforge.com/minecraft/mc-mods/atmospheric) all have additions to potions and brewing.

**Comment by i-o-u** [comment]
Also I just realised Quark has their own glowshrooms so that's a bit of an issue with compatibility

![2020-04-05_19 40 56](https://user-images.githubusercontent.com/60834747/78471549-6bb31980-7775-11ea-9516-55e2928199cb.png)

**Comment by cech12** [comment]
Okay that could be an issue. ^^ I planned a magic component with fairy rings. A new crafting variant. That is not very vanilla like. So, be a friend mod could be difficult. But a better compatibility with this mod is possible. :)

The glowshroom could be an issue, too. 🤔 I will look at it :)

**Comment by cech12** [comment]
I opened a project for supporting Quark: https://github.com/cech12/ExtendedMushrooms/projects/4
This issue is only to support Vertical Planks and Vertical Slabs

**Comment by cech12** [comment]
Also support it for the following mods:
* https://www.curseforge.com/minecraft/mc-mods/i-like-wood
* https://www.curseforge.com/minecraft/mc-mods/vanilla-things (only vertical slabs)
* https://www.curseforge.com/minecraft/mc-mods/extended-slabs (only vertical slabs)
* https://www.curseforge.com/minecraft/mc-mods/extended-slabs-1-15 (only vertical slabs)
* Double Slabs (planned feature) (only vertical slabs)
* https://www.curseforge.com/minecraft/mc-mods/slabs-stairs-walls
* Mubble? https://www.curseforge.com/minecraft/mc-mods/mubble

**Comment by Blackout03** [comment]
> Also support it for the following mods:
> 
> * https://www.curseforge.com/minecraft/mc-mods/i-like-wood
> * https://www.curseforge.com/minecraft/mc-mods/vanilla-things (only vertical slabs)
> * https://www.curseforge.com/minecraft/mc-mods/extended-slabs (only vertical slabs)
> * https://www.curseforge.com/minecraft/mc-mods/extended-slabs-1-15 (only vertical slabs)
> * Double Slabs (planned feature) (only vertical slabs)
> * https://www.curseforge.com/minecraft/mc-mods/slabs-stairs-walls
> * Mubble? https://www.curseforge.com/minecraft/mc-mods/mubble

ooh nice to see my mod (https://www.curseforge.com/minecraft/mc-mods/extended-slabs-1-15) which is a continuation of (https://www.curseforge.com/minecraft/mc-mods/extended-slabs) both mentioned here lol

**Comment by cech12** [comment]
I searched mods with these features to support them and found yours, too. How did you find this issue? :D

**Comment by Blackout03** [comment]
I searched extended on a modpack launcher thing and saw Extended Mushrooms and ended up here lol
