### ISSUE TITLE
java.lang.Exception: Too many AI Tasks

### ISSUE THREAD

**Issue by didis54** [cech12/ExtendedMushrooms#26]
Hi,

I'm linking to this error I got on my server;
https://github.com/ldtteam/Performant/issues/32

Thanks you.

**Comment by cech12** [comment]
Okay, thats weird. I only add one goal at this point. I will look at this, thanks for reporting it!

**Comment by cech12** [comment]
I fixed it and in the next version you wont get any errors about this issue. 
Thanks for your report!  😄

**Comment by cech12** [comment]
The fix was released in version 1.3.0
