### ISSUE TITLE
2 new mushrooms for the Fairy Ring crafting

### ISSUE THREAD

**Issue by cech12** [cech12/ExtendedMushrooms#55]
Decide which 2 new mushrooms should be added. (ideas: https://github.com/cech12/ExtendedMushrooms/projects/1)

**Comment by Blackout03** [comment]
The Cloudy, Slimey and Honey ones are my favourite of them. The Fairy one though it has Fairy in the name just like the Fairy Ring. It doesn't have any extra behaviours or items with it.

**Comment by cech12** [comment]
@Blackout03 thanks for your feedback! :) I will take it into account in my decision. :)
