### ISSUE TITLE
[Feature]: This mod is awesome

### ISSUE THREAD

**Issue by riskable** [cech12/ExtendedMushrooms#69]
### Describe the Feature

I just wanted to say that I really love this mod.  I've played on three servers with it now and on each one my knowledge of the mushroom Fairy Circle has been like an early game superpower!  Everyone is like, "How TF do you have so much honeycomb already‽"  Ahahaha I love it.

Everyone thinks this mod is just for decoration and they couldn't be more wrong!  Keep up the great work 👍

**Comment by cech12** [comment]
Thanks for your nice feedback! :) If you have any suggestions for this mod, please let me know. Have fun with this mod! :)
