### ISSUE TITLE
[Feature]: Ability to make nether fungi (Crimson Fungus and Warped Fungus)

### ISSUE THREAD

**Issue by riskable** [cech12/ExtendedMushrooms#70]
### Describe the Feature

It would be nice if we had a Fairy Ring recipe for making Crimson Fungus and Warped Fungus.  No idea what the recipe should be (Nether Wart + Red/Cyan dye?) but it sure would be useful and fit with the mod.

**Comment by cech12** [comment]
Thanks for your feature request! I like the idea :) When I have time I will think about a good and fitting recipe :)

**Comment by cech12** [comment]
@riskable I have added some new nether related recipes and enable the possibility to buildup a fairy ring from nether fungi as well. The changes are published in mod version 1.19.4-3.2.0.0
