### ISSUE TITLE
[Bug]: Mega mushrooms grow through blocks

### ISSUE THREAD

**Issue by IdrisQe** [cech12/ExtendedMushrooms#84]
### Minecraft Version

1.19.2

### Forge Version

43.3.5

### Mod Version

3.0.1.4

### Modpack or other Mod

https://www.curseforge.com/minecraft/modpacks/cottage-witch/files/5218654
Cottage Witch version 1.16.2hotfix

### Describe the Issue

When placing red mushrooms on some Organic Compost from Farmer's Delight, twice they instantly and spontaneously grew into Mega Red Mushrooms, going straight through the floor of our basement and completely messing up our house. They really shouldn't be able to grow if solid blocks are in the way.

The space in question (it was a 2x2x2 space in the corner):
![image](https://github.com/cech12/ExtendedMushrooms/assets/40530630/068b4bad-e257-443b-a50c-36bdece7dcc9)

**Comment by cech12** [comment]
Thanks for your report! I will look into that when I have time :) It should be an incompatibilty with the compost blocks. For now you should avoid using the compost blocks as ground for the mushrooms.

**Comment by cech12** [comment]
I have found the issue and fixed it in the upcoming versions:
- 1.20.1-4.1.0.2
- 1.19.4-3.2.0.1
- 1.19.2-3.0.1.5

Thanks again for your report! That was a really bad bug, sorry for that. :/

**Comment by IdrisQe** [comment]
No problem! I'm glad to see it fixed so fast!

One more thing - not sure if it's a bug, or some weird interaction with our modpack, so I don't want to make an issue for it, but on 3.0.1.4, whenever we use the Fairy Ring, specifically on dirt blocks in a dark area, the ring explodes after making a single recipe. As in several of the mushrooms that make up the ring will just break off. I assume this has to do with the fact that dirt, unlike Podzol or Mycelium, only supports mushrooms if they're in low-light, and the Fairy RIng generates light when doing a recipe, thereby breaking itself... But I'm not certain if that's the cause. Do you have any idea what could be causing it?

**Comment by cech12** [comment]
Interesting finding as well^^ I think that has something to do with the light level, which changes when the fairy ring is active. It is too high for the mushrooms that can only be placed in dark areas. A block update seems to break them. I will look into that as well :)

**Comment by cech12** [comment]
@IdrisQe I have found the issue and fixed it in the upcoming versions:
- 1.20.1-4.1.0.3
- 1.19.4-3.2.0.2
- 1.19.2-3.0.1.6
