### ISSUE TITLE
[Bug]: Worldgen Breaking Other Structures

### ISSUE THREAD

**Issue by 7OOTnegaTerces** [cech12/ExtendedMushrooms#88]
### Minecraft Version

1.20.1

### Forge Version

47.1.106

### Mod Version

4.1.3.1

### Modpack or other Mod

Using NeoForge 47.1.106, not Forge, but for 1.20.1 they're interchangeable.

Choice Theorem's Overhauled Village v3.4.5 https://www.curseforge.com/minecraft/mc-mods/choicetheorems-overhauled-village

### Describe the Issue

This mod's worldgen happens after Choice Theorem's, which causes the latter's mushroom village structures to be destroyed by this mod's added mushrooms.  I'd much prefer the other way, as not only would it look better, but it would make more sense for the villagers to chop down mushrooms to build their village, than for the mushrooms to chop down the village.

**Comment by cech12** [comment]
THanks for your report! I will look into that when I have time :)

**Comment by cech12** [comment]
@7OOTnegaTerces Sorry for my late answer. Could you add some screenshots of your issue?
Ich have tested around a bit and could not find such destroying behaviour.

![grafik](https://github.com/user-attachments/assets/1e134cd6-7bed-4ac7-a7f0-c8002e67a355)
(looks fine to me)

Used mod versions:
- Extended Mushrooms 1.20.1-4.1.3.1
- ChoiceTherorem's Overhauled Village 3.4.9b

**Comment by 7OOTnegaTerces** [comment]
Oh, sorry, I forgot to come back and close this!  It was actually a different mushroom mod that was the issue, not yours!  Thanks for all the new mushrooms, especially the underground ones!  Though I kinda feel like the poison released by the poison mushrooms are not quite in line with the “totally safe, nothing will try to kill you” special theme of the mushroom biome, as it doesn’t **actually** kill you, I suppose it’s _okay_.  Thanks for this mod!!!
