### ISSUE TITLE
[Bug]: Ticking block entity crash when using hopper to insert a valid fairy ring recipe

### ISSUE THREAD

**Issue by coolbot100s** [cech12/ExtendedMushrooms#89]
### Minecraft Version

1.20.1

### Forge Version

47.3.11

### Mod Version

4.1.3.1

### Modpack or other Mod

none/any

### Describe the Issue

A hopper placed above and facing into a fairy ring will push items into the fairy ring, however they will not render until the entity is reloaded.  

When a valid recipe is inserted into the fairy ring, the server will crash instantly, in this case, I've attempted the recipe vine+red dye.  

### Logs

https://mclo.gs/Im2lNgz https://mclo.gs/jTAPYQP

### Do you use any performance-enhancing mods (e.g. OptiFine)?

none

**Comment by cech12** [comment]
@coolbot100s thank you for your report! I will look into that when I have time. :)

**Comment by cech12** [comment]
@coolbot100s The issue is fixed in the upcoming version 1.20.1-4.1.3.2. Thanks again for your report!
